name: Generate 3D Models
on: [push, pull_request]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix build
    - uses: actions/upload-artifact@v4
      with:
        name: models
        path: result/
